version: '3'
services:
  postgres:
    container_name: postgres
    build:
      context: .
      dockerfile: ./docker/postgres/Dockerfile
    environment:
      - POSTGRES_USER=takoshin
      - POSTGRES_PASSWORD=Ts1997522
      - POSTGRES_DB=app_db
      - TZ=Asia/Tokyo
    ports:
      - 5432:5432


  app:
    container_name: app
    depends_on:
      - postgres
    build: 
      context: .
      dockerfile: ./docker/golang/Dockerfile
    environment:
      - TZ=Asia/Tokyo
    volumes:
      - ./:/go/src/app
    ports:
      - "8080:8080"


